spring.application.name=Student
spring.profiles.active=mysqlp
spring.flyway.enabled=false

#h2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update